FinalProjectHenry/BackEnd

src/Models/Product.js

New file src/Models/Product.js

feat(models/Product) : add Models/Product.js

---

src/Models/Cart.js

feat(models/Cart): add file Cart.js

---

src/Models/User.js

Se agregraron nuevos campos en el modelo de usuarios según el diagrama entidad-relacion, lo campos fueron los siguientes:
phone -> Teléfono del usuario
postalCode -> Códgio postal del usuario
nickName -> Nombre que usará el usuario en el sistema
address -> Dirección del usuario

feat(models/User): add fields

---

src/Models/Cart.js
src/Models/TypePerson.js
src/Models/User.js

Se ha añadido un modelo nuevo para establecer el tipo de persona
Contendrá datos que no cambiarán, por lo menos por ahora:
Serian Persona Física o Natural
y Persona Jurídica

feat(models/TypePerson): add model TypePerson

---

src/Models/TypeUser.js

Nuevo modelo agregado, para identificar el tipo de usuario que estará en el sistema, sea comprador, vendedor, incluso ambos o administrador.
También uniformidad en los demás archivos para conservar un tipo de escritora en los modelos

feat(models/TypeUser): add models TypeUser

---

src/Models/ShoppingHistory.js

Creating ShoppingHistory Model

Add: ShoppingHistory Model

---

index.js
src/Models/TypePerson.js
src/Models/TypeUser.js
src/Models/User.js
src/Mutation/Mutation.js
src/Mutation/addUser.js
src/db.js
src/schema.js

Cambios en el schema de Usuario y mutacion
Se agregaron los campos que están en los modelos de sequelize para que pueda actualizar la informacion correctamente

(schema User): changes schemas and mutation user

---

src/Models/Product.js
src/Models/User.js
src/Mutation/Mutation.js
src/Mutation/addProduct.js
src/Query/Query.js
src/Query/allProducts.js
src/db.js
src/schema.js

Cambios añadidos dentro del esquema de productos y mutaciones.
Dentro de las mutaciones solo se pueden agregar productos
Añadido también el campo para borrado lógico en usuarios.

feat(product): added changes on product schemas

---

src/Models/ShoppingHistory.js
src/Mutation/Mutation.js
src/Mutation/addCart.js
src/Mutation/addShoppingHistory.js
src/Mutation/addTypePerson.js
src/Mutation/addTypeUser.js

Mutaciones agregadas para todos los modelos puedan agregar nuevos campos

feat(mutations/): added changes on mutations

---

src/Query/Query.js
src/Query/allCart.js
src/Query/allShoppingHistory.js
src/Query/allTypePerson.js
src/Query/allTypeUser.js

Se crearon los archivos "all..." en la carpeta Query
Se importaron dentro del archivo Query.js

feat(Query): added allFiles on Query

---

src/Models/ShoppingHistory.js
src/schema.js

Add: features schemas

---

index.js
src/Models/Cart.js
src/Models/Product.js
src/Models/ShoppingHistory.js
src/Models/User.js
src/Mutation/Mutation.js
src/Mutation/addProduct.js
src/Mutation/addUser.js
src/db.js
src/schema.js

Cambios hechos en el modelo de productos para agregar imagen,
modelo de usuarios para agregar imagen del perfil.

feat(db): added changes in db

---

src/Models/User.js

Cambios en el modelo de usuario

refactor(models/user): change fields

---

src/Models/User.js
src/Mutation/addUser.js
src/db.js

Relaciones comentadas de tipos de suaurios y tipos de personas para que por ahora no nos causen problema

feat(models/User): comment user type relationships

---

src/Models/Material.js
src/Mutation/Mutation.js
src/Mutation/addMaterial.js
src/Query/Query.js
src/Query/getAllMaterial.js
src/db.js
src/schema.js

Se agrego modelo "material" para filtrados por categorias.
Se agrego modelo "material" en archivo db.js
Se agrego "type material"  en archivo "schema.js
Se agrego mutation "addMaterial" para agregar material a producto (ver conexión entre estas tablas cuando este listo el modelo de producto)

feat (Models/Material): add material ("categories")

---

src/db.js

Borre una linea que estaba demas dentro del archivo db.js para evitar errores. Solo se repetian lo modelos

an extra line was deleted to avoid conflict

---

src/Mutation/Mutation.js
src/Mutation/deleteProduct.js
src/Query/allProductsByUser.js
src/db.js

Corregí una palabra e hice la relación del material producto.

feat(server) add deleteProduct mutation

---

package-lock.json

Añadido la depedencia de cloudinary dentro del package-lock.json

feat: add package cloudinary in package-lock

---

src/Models/Material.js
src/Mutation/addMaterial.js

Se agrega imagen para los materiales

feat (Models/materials.js) add image

---

package-lock.json
package.json

se agrega bcryptjs a package.json

feat (package.json) add bcryptjs

---

package-lock.json
package.json
src/Mutation/addProduct.js
src/Query/allProducts.js
src/db.js
src/schema.js

He cambiado los productos para que traiga los productos

feat: added changes in materials

---

src/Models/Material.js
src/Mutation/Mutation.js
src/schema.js

Se soluciono conflicto producido al agregar imagen al modelo Material.

Franco arreglando todo

---

src/Query/getUserById.js

Agregado que cuando se pide el detalle del usuario se coloque el modelo de producto tambien

feat(getUserById): add models product

---

index.js
src/Mutation/addProduct.js
src/Mutation/uploadProductImg.js
src/schema.js

- En el archivo addProduct se agrego la funcion de uploadProductImg para cargar la url de cloudinary a la base de datos.
- En el archivo schema.js se cambio del type Product el userId y Material a String
-  se cambio el force a true

feat(addProduct): add url cloudinary

---

src/Mutation/addMaterial.js
src/Mutation/addProduct.js
src/Query/Query.js
src/Query/allProducts.js
src/Query/filteringMaterial.js
src/Query/orderingPrice.js
src/Query/orderingStock.js
src/schema.js

Se cambió el schema para que traiga el modelo de material bien, ademas de arreglar el filtro aunque falta combinas.
ordenamiento ya trae la tabla de material asociada

feat(filteres/query): add changes in filtering name

---

src/Mutation/addProduct.js

Mi culpa, hubo un conflicto y se me pasó un error

Errorcito dentro de addProduct.js

---

src/Mutation/Mutation.js
src/Mutation/addMaterial.js

Se corrigio logica en addMaterial
Se agrego prop image en Mutations (addMaterial)

feat(addMaterialLogic)Fran

---

src/utils/Materials.js

Agregada un campo imagen dentro de materials para cada registro

feat(utils/materials): add image in schema

---

src/Query/Query.js

Se eliminó el otro filtro que no era necesario

fix: delete filteringFipCondition

---

src/Query/allProductsByUser.js

añadida la relacion dentro del query que trae todos los productos de un usuario

fix(query): added relation in productsbyUser

---

index.js
src/Models/Profile.js
src/Mutation/Mutation.js
src/Mutation/google.js
src/Mutation/singUp.js
src/Query/allUsers.js
src/Query/getUserById.js
src/schema.js
src/utils/Profile.js

Se agrega mutación para carga de datos en DB de usuario logeado con google

feat(google.js) add mutation google.js to create DB google user

---

src/Query/Query.js
src/Query/filterUnion.js
src/Query/getUserById.js
src/schema.js

Hecha la union de filtros y ordenamientos con el  back
falta comprobacion si funciona en el front

feat(filtering union): added changes by filtering union

---

index.js

Los usuarios de prueba se enctriptaron

Release(index): Fix encrypt password

---

src/Models/Product.js
src/Models/User.js
src/Mutation/deleteUser.js
src/Mutation/restoreProduct.js

No tocar nada, tengo un servidor de prueba, quiero intentar otras cosas
- Se agregó la columna deletedAt al producto

feat(Server): Add deleteWithParainoid on Product model. Add restore function (I'm still tryin' it )

---

src/Query/searchUserByName.js

Se puede buscar un usuario por nombre, apellido o email

feat(search): added search of fields lastname and email

---

src/Query/Query.js
src/Query/getProductById.js

Agregue esta query para el detalle de cada producto

feat(getProductById) 

---

src/Mutation/google.js
src/Mutation/login.js

se modifica mutation/google, ahora siempre devuelve idUser, name, lastname, email del usuario logeado con google
se elimina en mutation/google condición que pedía token de google para validación

fix(google.js)refact google.js

---

src/Mutation/google.js

se resuelve creacion de usuario y perfil con google. ahora permite ingresar los datos del formulario y crea perfil correctamente

fix(google.js) add perfil creation whith User creation

---

src/Models/Profile.js
src/Mutation/Mutation.js
src/Mutation/deleteProfile.js
src/Mutation/deleteUser.js
src/Mutation/restoreProduct.js
src/Mutation/restoreProfile.js
src/Mutation/restoreUser.js

Updates, soft delete and restoring

feat(Server): Add updates &  soft delete on Profile, Product and User

---

src/Mutation/Mutation.js
src/Mutation/orderMercadoPago.js
src/schema.js

Se modifica el esquema de orderMercadoPago para que reciba un arreglo de productos.
El arreglo debe contener objetos con: 
- El producto que se compra
- currentId : la moneda en la que se realiza la compra
- quantity: la cantidad a comprar.
Devolvera los productos que se van a comprar, un arreglo con la moneda de la transaccion de cada producto, y un string con la respuesta de mercadopago

schema.js: change ordermercadopago

---

src/schema.js

fix(schema.js)fix error schema.js

---

src/Models/Material.js
src/Mutation/Mutation.js
src/Mutation/deleteMaterial.js
src/Mutation/restoreMaterial.js
src/Mutation/updateMaterial.js

Add mutations:  update and softDelete on Material model

feat(Server): Add update and SoftDelete on Material model

---

src/Mutation/orderMercadoPago.js
src/Query/Query.js
src/Query/feedbackMercadoPago.js
src/schema.js

se agrega query feedback MercadoPago.

feat(feedbackmercadopago):add query feedbackMercadoPago

---

src/Query/allProductsByUser.js
src/Query/getUserById.js

Se solucionaron conflictos de modelo Materials

MaterialsFixed

---

src/Mutation/Mutation.js
src/Mutation/orderMercadoPago.js
src/helper/filters.js

se cambia la respuesta de ordermercadopago

fix(orderMercadoPago) change response

---

src/Query/Query.js
src/Query/filterUnion.js
src/Query/getMaterialsByName.js

cambios para complementar el filtro de submaterial, buscando categorias por nombre

feat(material name): added changes material name for filter submaterial

---

src/Models/Materials.js
src/Models/SubMaterials.js
src/Mutation/Mutation.js
src/Mutation/deleteProduct.js
src/Mutation/deleteSubMaterial.js
src/Mutation/restoreMaterial.js
src/Mutation/restoreProduct.js
src/Mutation/restoreProfile.js
src/Mutation/restoreSubmaterial.js
src/Mutation/restoreUser.js
src/Query/Query.js
src/Query/allSubmaterials.js

update n SoftDelete Submaterial and Fix all softDelete

feat (Server): Add update n SoftDelete Submaterial and Fix all softDelete

---

index.js
src/Mutation/addProduct.js
src/resolvers.js

resuelto conflicto con average Rating del producto

fix: conflict resolver

---

index.js
src/Mutation/userRegister.js

Se estilizo el mail de verificación que llega al correo y ahora se ve mas profesional

Fix: Fix email message

---

index.js

Se cargan las relaciones con productos de materiales y submateriales en las tablas intermedias para visualizar data y filtrados

feat(index): data preload

---

src/Query/allUsers.js

Se estructura información de respuesta. Todos los objetos incluidos en la consulta Allusers (profile, shoppinghistory y demas) no se estaba trayendo cuando se realiza la consulta.
Ahora entrega un arreglo de objetos con la información de usuario y la de perfil.
Cómo entrega la información: 
"allUsers": [
{
"idUser": "2a7b2d7c-7d26-4c95-98bc-a21c84ef8f1d",
"name": "Juan",
"lastname": "Pérez",
"email": "juanperez@example.com",
"password": "$2a$08$aEBrXoHGVgrp3qkJwGyGXObs4vErQZfBXImGJMsbLQF/mo/gXCfGe",
"acountActive": null,
"termsAndCondsAprove": false,
"deleteAd": null,
"profile": {
"idProfile": "a57ddc4e-a4fd-4120-8c79-a01506277c34",
"userName": "pepito",
"cuitCuil": "11-12345678-1",
"phone": "+54 9 3512 7684 21",
"address": "Av Colon 125",
"postalCode": "5000",
"description": "Este es el …

fix (allUsers.js) : structure response

---

src/Query/allUsers.js

Se cambia variable accountActive a acountActive (nombre que figura en el modelo Users). Ahora trae la información correctamente

fix: allusers.js: change accountActive to acountActive

---

src/Query/Query.js
src/Query/getShoppingHistoryByUser.js

_Se agrega consulta para buscar el historial completo de compras del usuario._
- **getShoppingHistoryByUser:** recibe por parametro el ID del usuario. Recupera su historial de compras. Devuelve un arreglo con las compras realizadas por el usuario.
**Consulta:**
```
query GetShoppingHistorybyUser($userId: ID!) {
getShoppingHistorybyUser(userId: $userId) {
IDShopHistory
operationId
paymentMethod
paymentMethodId
netAmount
taxes
totalAmount
UserIdUser
}
}
```
**Respuesta:**
```
{
"data": {
"getShoppingHistorybyUser": [
{
"IDShopHistory": "4163e037-95de-4ef4-9268-57642d1d654b",
"operationId": 1327154320,
"paymentMethod": "credit_card",
"paymentMethodId": "visa",
"netAmount": 233.67,
"taxes": 0,
"totalAmount": 243.66,
"UserIdUser": "2475fb41-02c1-44bd-8c02-ac26a0d784f6"
},
{
"IDShopHistory": …
```

feat (getshoppinghistorybyuser) add new query

---

src/Query/filterUnion.js

Cuando se deselecciona la categoría/material cuando se esta en la sección de filtrados, ahora si puede dar todo el arreglo de productos

fix: fixed when filtering

---

src/Query/filterUnion.js

Arreglado que al marcar o desmarcar una subcategoria dentro de la seccion de filtrados devuelva el arreglo que ya se tenia.

fix(filterUnion): fixed upon receiving an empty array of subcategories

---

index.js

Se agrega try catch para manejo de errores. Se soluciona un error que generaba una interrupción del server cuando se generaba un pago

fix(index.js)add try catch

---

index.js
src/utils/Users.js

Se agrega en Utils/Users.js el campo role para poder generar los usuarios hardcodeados en la base de datos.
Se importa role en la creacion de la base de datos.

 fix(utils/users.js)add role on users

---

index.js
src/Models/ShoppingHistory.js

Se agrega campo status en el modelo shoppinghistory. El mismo tiene formato string, y se cargará con la informacion que entrega mercadopago como respuesta a la resolucion de la compra (approved, rejected, pending)

feat(shoppinghistory)add status field on model shoppinghistory

---

index.js
package-lock.json
package.json
src/Models/ShoppingHistory.js
src/Models/User.js

Limite establecido para la imagen.
Rol del usuario predeterminado

feat(index.js): limit in image on express

---

index.js

Se cambia valor que se agrega en operationId

fix(index.js/webhook)change operationId value to id

---

src/Query/getShoppingHistoryByUser.js
src/schema.js

se agrega cambio en la mutación shoppinghistoryuser para permitir agregar status en la tabla de historial de compras.

fix(shoppinghistoryuser)add status field

---

src/Mutation/orderMercadoPago.js

changes order mercado

---

src/Mutation/orderMercadoPago.js

agregadas dos variables de entorno

un cambio mas

---

index.js

se agrega variable de entorno PORT en listen de server para deploy

feat (index.js) add env PORT

---

index.js

se reestablecen las lineas comentadas. se pasa base de datos a false

feat(index.js)restore commented lines

---

src/db.js

Necesito hacer la prueba para comprobarlo con vercel

Actualizando variable de entorno POSTGRES

---

src/Models/Profile.js
src/Mutation/Mutation.js
src/Mutation/banProfile.js
src/Mutation/switchRole.js
src/Mutation/updateMaterial.js
src/Mutation/updateProduct.js
src/Mutation/updateProfile.js
src/Query/Query.js
src/Query/allProductsAdminDash.js
src/schema.js

Added:
- AllProducts: Only for Admin Dashboard
- switRole: Switch role from Admin Dahsboard (user or admin) for giving permissions
-  banProfile: ban profile permanently by Cuit/Cuil

feat(Server): Add feature allProducts, switchRole, banProfile for adminDashboard

---

index.js

Habilitada la idea introspección para producción

fix(index): enable introspection

---

index.js

principalmente para colocar los cambios que se hagan dentro de la base de datos

Colocando force en true

---

src/Mutation/Mutation.js
src/Mutation/updateUser.js
src/Query/getUserById.js

Se agrego la propiedad role a la Mutation de updateUser 
y  a la query de getUserById

feat(role): add prop role

---

src/Mutation/addShoppingHistory.js

se agrega parametro status en mutation addShoppingHistory para que renderize correctamente en el perfil

feat(addshoppinghistory):add payment status

---

src/schema.js

feat(schema) add createdAt to type Blog

---

src/Mutation/Mutation.js
src/Mutation/banProfile.js
src/utils/Profile.js

Se corrigio la mutacion de banProfile

fix(banProfile): changed the structure of banProfile.js

---

src/Mutation/updateBlog.js

fix(updateBlog)change arguments

---

src/Mutation/Mutation.js
src/Mutation/restoreProduct.js
src/Query/Query.js
src/Query/allRestoredBlogs.js
src/Query/allRestoredMaterials.js
src/Query/allRestoredProducts.js
src/Query/allRestoredProductsByUser.js
src/Query/allRestoredProfile.js
src/Query/allRestoredSubmaterials.js
src/schema.js

Cambios para que se puedan eliminar y restaurar productos

feat(products): added changes in destroy and restore products

---

src/Query/allShoppingHistory.js

Se cambio la query para que incluya buyOrders

fix(Query/allShoppingHistory.js): changed the structure

---

src/Query/allUsers.js

add models.Review

---

src/Models/Blog.js

type STRING (255)characters for type TEXT

fix(Blog.js) fix Model Blog in blog.description 

---

src/Query/allProductsAdminDash.js

Se agrego en la query de AllproductsAdmin que incluya el modelo de Review

feat(Review): add models.Review

---

src/Mutation/addShoppingHistory.js
src/Mutation/stock.js

agregando feature stock para la resta y eliminacion de cada publicacion al comprar

feature stock and reduce stok addShoppingHistory

---

src/Mutation/Mutation.js
src/Mutation/addMaterial.js
src/Mutation/restoreMaterial.js
src/Query/allRestoredMaterials.js
src/Query/searchUserByName.js
src/schema.js

Crud de materiales donde se arreglaron varios archivos para adaptarse al front

feat(materials): added changes in create, destroy and restore materials

---

src/Mutation/addShoppingHistory.js
src/Mutation/sendShoppingHistory.js

agregando envio de correo al realizar una compra falta estilado

feature sendShoppingHistory

---

src/Mutation/Mutation.js
src/Mutation/updatePasswordRec.js

fix(Server): Fix updatePassword

---

src/Mutation/sendShoppingHistory.js

agregando estilizado de correo de compra

feat envio de correo de confirmacion de compra

---

src/Query/allUsers.js
src/Query/getUserById.js

Resuelto error que no permite obtener usuarios por un dataValues undefined

fix: resolve datavalues undefined in allUsers and UsersByID

---

src/Query/Query.js
src/Query/getMaterialById.js

Busqueda de material por ID para facilitar la actualizacion del material

feat(materials): search material by id

---

src/Query/allRestoredUser.js

Solución a problema que evitaba que se trajeran todos los usuarios que han sido eliminados

fix(allRestoredUser): resolve problem dataValues undefined
